version: '2'

services:
  social-network:
    build:
      context: .
      args:
        - no-cache
    ports:
      - "8080:8080"
    depends_on:
      - pgmaster
      - pgslave
      - tarantool
      - rabbitmq
    networks:
      - pgnet
  pgmaster:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/pgmaster:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - pgnet
  pgslave:
    image: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./volumes/pgslave:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    depends_on:
      - pgmaster
    networks:
      - pgnet
  tarantool:
    image: tarantool/tarantool
    ports:
      - "3301:3301"
    networks:
      - pgnet
  rabbitmq:
    image: arm64v8/rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - pgnet
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "citusdata/citus:12.1.3"
    ports: [ "25432:5432" ]
    labels: [ "com.citusdata.role=Master" ]
    environment: &AUTH
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "social_network"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  worker:
    image: "citusdata/citus:12.1.3"
    labels: [ "com.citusdata.role=Worker" ]
    depends_on: [ manager ]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
    deploy:
      replicas: 1
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [ master ]
    environment: *AUTH
networks:
  pgnet:
volumes:
  healthcheck-volume: