version: '2'

services:
  social-network-main-1:
    container_name: social-network-main-1
    build:
      context: social-network-main/.
      args:
        - no-cache
    ports:
      - "8090:8090"
    depends_on:
      - pgmaster
      - pgslave
      - tarantool
      - rabbitmq
      - social-network-dialog
    networks:
      - pgnet
    environment:
      - DB_NAME=social_network
      - DB_M_SERVER=haproxy
      - DB_M_PORT=5001
      - DB_M_USER=postgres
      - DB_M_PASS=postgres
      - DB_S_SERVER=haproxy
      - DB_S_PORT=5001
      - DB_S_USER=postgres
      - DB_S_PASS=postgres
      - DB_SH_SERVER=master
      - DB_SH_PORT=5432
      - DB_SH_USER=postgres
      - DB_SH_PASS=postgres
      - TARANTOOL=tarantool
      - TARANTOOL_PORT=3301
      - TARANTOOL_PORT=3301
      - TARANTOOL_USER=guest
      - TARANTOOL_PASS=
      - RABBIT_MQ=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=main1
      - RABBIT_PASSWORD=main1
      - DIALOG_SERVER_NAME=social-network-dialog
      - DIALOG_SERVER_PORT=8081
      - PORT=8090
  social-network-main-2:
    container_name: social-network-main-2
    build:
      context: social-network-main/.
      args:
        - no-cache
    ports:
      - "8091:8091"
    depends_on:
      - pgmaster
      - pgslave
      - tarantool
      - rabbitmq
      - social-network-dialog
      - social-network-main-1
    networks:
      - pgnet
    environment:
      - DB_NAME=social_network
      - DB_M_SERVER=haproxy
      - DB_M_PORT=5001
      - DB_M_USER=postgres
      - DB_M_PASS=postgres
      - DB_S_SERVER=haproxy
      - DB_S_PORT=5001
      - DB_S_USER=postgres
      - DB_S_PASS=postgres
      - DB_SH_SERVER=master
      - DB_SH_PORT=5432
      - DB_SH_USER=postgres
      - DB_SH_PASS=postgres
      - TARANTOOL=tarantool
      - TARANTOOL_PORT=3301
      - TARANTOOL_PORT=3301
      - TARANTOOL_USER=guest
      - TARANTOOL_PASS=
      - RABBIT_MQ=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=main2
      - RABBIT_PASSWORD=main2
      - DIALOG_SERVER_NAME=social-network-dialog
      - DIALOG_SERVER_PORT=8081
      - PORT=8091
  social-network-dialog:
    build:
      context: social-network-dialog/.
      args:
        - no-cache
    ports:
      - "8081:8081"
    depends_on:
      - tarantool
    networks:
      - pgnet
    environment:
      - TARANTOOL=tarantool
      - TARANTOOL_PORT=3301
      - TARANTOOL_PORT=3301
      - TARANTOOL_USER=guest
      - TARANTOOL_PASS=
  pgmaster:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/pgmaster:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - pgnet
  pgslave:
    image: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./volumes/pgslave:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    depends_on:
      - pgmaster
    networks:
      - pgnet
  tarantool:
    image: tarantool/tarantool
    ports:
      - "3301:3301"
    networks:
      - pgnet
  rabbitmq:
    image: arm64v8/rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - pgnet
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "citusdata/citus:12.1.3"
    ports: [ "25432:5432" ]
    labels: [ "com.citusdata.role=Master" ]
    environment: &AUTH
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "social_network"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - pgnet
  worker:
    image: "citusdata/citus:12.1.3"
    labels: [ "com.citusdata.role=Worker" ]
    depends_on: [ manager ]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
    deploy:
      replicas: 1
    networks:
      - pgnet
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [ master ]
    environment: *AUTH
    networks:
      - pgnet
  haproxy:
    build:
      context: haproxy/.
      args:
        - no-cache
    ports:
      - "5001:5001"
      - "7001:7001"
    depends_on:
      - pgmaster
      - pgslave
    networks:
      - pgnet
  nginx:
    image: nginx:1.21
    ports:
      - "4088:80"
      - "4080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pgnet
    depends_on:
      - social-network-main-1
      - social-network-main-2
networks:
  pgnet:
volumes:
  healthcheck-volume: